/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClimaRouteImport } from './routes/clima'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AnimaisRouteImport } from './routes/animais'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimaRoute = ClimaRouteImport.update({
  id: '/clima',
  path: '/clima',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisRoute = AnimaisRouteImport.update({
  id: '/animais',
  path: '/animais',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/animais': typeof AnimaisRoute
  '/assinatura': typeof AssinaturaRoute
  '/clima': typeof ClimaRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/animais': typeof AnimaisRoute
  '/assinatura': typeof AssinaturaRoute
  '/clima': typeof ClimaRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/animais': typeof AnimaisRoute
  '/assinatura': typeof AssinaturaRoute
  '/clima': typeof ClimaRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/animais'
    | '/assinatura'
    | '/clima'
    | '/login'
    | '/precos'
    | '/relatorios'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/animais'
    | '/assinatura'
    | '/clima'
    | '/login'
    | '/precos'
    | '/relatorios'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/animais'
    | '/assinatura'
    | '/clima'
    | '/login'
    | '/precos'
    | '/relatorios'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnimaisRoute: typeof AnimaisRoute
  AssinaturaRoute: typeof AssinaturaRoute
  ClimaRoute: typeof ClimaRoute
  LoginRoute: typeof LoginRoute
  PrecosRoute: typeof PrecosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clima': {
      id: '/clima'
      path: '/clima'
      fullPath: '/clima'
      preLoaderRoute: typeof ClimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais': {
      id: '/animais'
      path: '/animais'
      fullPath: '/animais'
      preLoaderRoute: typeof AnimaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnimaisRoute: AnimaisRoute,
  AssinaturaRoute: AssinaturaRoute,
  ClimaRoute: ClimaRoute,
  LoginRoute: LoginRoute,
  PrecosRoute: PrecosRoute,
  RelatoriosRoute: RelatoriosRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
